# Builds the User Service Docker Image on Docker Hub

FROM frolvlad/alpine-oraclejdk8:slim

MAINTAINER Gary A. Stafford <garystafford@rochester.rr.com>
ENV REFRESHED_AT 2016-08-13

# install jar from GitHub
ENV GITHUB_REPO https://github.com/garystafford/microservice-docker-demo-user/raw/build-artifacts
ENV APP_FILE user-service-0.1.0.jar

RUN set -ex \
  && apk --no-cache add --virtual .build-dependencies curl \
  && curl -fsSL ${GITHUB_REPO}/${APP_FILE} -o /app.jar \
  && sh -c 'touch /app.jar'

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
